theme: jekyll-theme-modernist
show_downloads: false

title: "Brinda Sreenivas"

description: "Sophomore at University of Washington pursuing double major in Law, Societies & Justice (LSJ) and Political Science, with a minor in Data Science"
