theme: jekyll-theme-modernist
show_downloads: false

include:
  - assets/css/custom.css

title: "Brinda Sreenivas"

description: "Sophomore at University of Washington, Seattle WA studying to double-major in Law, Societies and Justice (LSJ) and Political Science with a minor in Data Science"
