theme: jekyll-theme-modernist
show_downloads: false

title: "Brinda Sreenivas"

description: "Sophomore at University of Washington pursuing double major in Political Science and Law, Societies & Justice (LSJ), and a minor in Data Science"
