remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: "Brinda Sreenivas"
description: "Sophomore at UW Seattle studying LSJ, Political Science, and minor in Data Science"
show_downloads: false
