remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme 

include:
  - assets/css/custom.css

title: "Brinda Sreenivas"

description: "Sophomore at University of Washington Seattle pursuing double-major in Political Science and Law, Societies and Justice, and minor in Data Science"
show_downloads: false
