remote_theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-remote-theme 

include:
  - assets/css/custom.css

title: "Brinda Sreenivas"

description: "Sophomore at University of Washington, Seattle WA studying to double-major in Law, Societies and Justice (LSJ) and Political Science with a minor in Data Science"
show_downloads: false
